---
# tasks file for nodejs
- import_playbook: nodepub.yml
- import_playbook: osarch.yml
- import_playbook: nodejs.yml
- name: Install global npm packages
  npm: global=yes name={{ item }} state=present
  with_items: "{{ nodejs_global_packages }}"
