---
# tasks file for nodejs
- include_tasks: nodepub.yml
- include_tasks: osarch.yml
- include_tasks: nodejs.yml
- name: Install global npm packages
  npm:
    global: yes
    name: "{{ item }}"
    state: present
  with_items: "{{ nodejs_global_packages }}"
